In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from pandas.plotting import scatter_matrix

In [2]:
# read csv file into pandas DataFrame 
data = pd.read_csv('data/train.csv')

In [3]:
data.shape

(486, 50)

In [4]:
# view first 5 columns of dataframe
data.head()

,pop,emp,emp_to_pop_ratio,hc,ccon,cda,cn,ck,ctfp,cwtfp,...,agriculture,fish,total_change,excl_energy_change,energy_change,metals_minerals_change,forestry_change,agriculture_change,fish_change,growthbucket
0,28.849621,6.914298,0.239667,1.547767,99010.171880,131991.375000,426543.343800,0.009374,0.648979,0.626111,...,149.37,876.46,0.264843,0.012115,0.717188,0.099935,-0.061177,0.073986,0.007576,0
1,45.728313,13.623806,0.297929,2.086037,316862.656300,374842.343800,804602.250000,0.019658,0.719390,0.657543,...,149.37,876.46,0.264843,0.012115,0.717188,0.099935,-0.061177,0.073986,0.007576,0
2,33.262043,13.323813,0.400571,1.498783,29762.876950,36584.992190,67072.593750,0.001670,0.308652,0.292607,...,149.37,876.46,0.264843,0.012115,0.717188,0.099935,-0.061177,0.073986,0.007576,0
3,8.025703,3.869000,0.482076,1.356151,6488.692871,7006.969727,5790.396973,0.000184,0.205865,0.234643,...,149.37,876.46,0.264843,0.012115,0.717188,0.099935,-0.061177,0.073986,0.007576,0
4,1.061468,0.243000,0.228928,1.676330,7620.187500,8419.264648,16907.236330,0.000431,0.959765,0.993985,...,149.37,876.46,0.264843,0.012115,0.717188,0.099935,-0.061177,0.073986,0.007576,0

In [5]:
# basic statistics about features
data.describe()

,pop,emp,emp_to_pop_ratio,hc,ccon,cda,cn,ck,ctfp,cwtfp,...,agriculture,fish,total_change,excl_energy_change,energy_change,metals_minerals_change,forestry_change,agriculture_change,fish_change,growthbucket
count,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,4.860000e+02,486.000000,486.000000,486.000000,...,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000
mean,20.185755,7.121089,0.357865,1.777389,64361.006942,80885.988722,2.442244e+05,0.004583,0.454419,0.453431,...,221.326667,1009.445556,0.044535,0.030346,0.082411,0.058144,0.024774,0.033930,0.023741,0.078189
std,30.037490,9.921471,0.080541,0.446339,129634.856793,156740.416624,4.725163e+05,0.008210,0.206562,0.203056,...,49.803981,140.125951,0.184025,0.105616,0.288454,0.151285,0.129924,0.127101,0.076937,0.268746
min,1.061468,0.243000,0.198212,1.069451,2781.259277,2984.366943,5.790397e+03,0.000124,0.098622,0.107790,...,149.370000,843.660000,-0.359446,-0.173741,-0.477017,-0.157564,-0.174550,-0.225998,-0.113858,0.000000
25%,3.830730,1.048750,0.297922,1.445886,9117.209716,11081.697755,2.429231e+04,0.000514,0.301179,0.295615,...,185.770000,899.190000,-0.058931,-0.044322,-0.102940,-0.053405,-0.060792,-0.026451,-0.020995,0.000000
50%,10.868272,4.184000,0.368841,1.689902,17471.495120,22228.022460,6.432356e+04,0.001355,0.400647,0.405870,...,213.095000,948.745000,0.061860,0.019950,0.054933,0.046808,0.003277,0.038444,0.006529,0.000000
75%,24.220695,8.517560,0.416717,2.117452,58016.873047,69676.791020,1.886244e+05,0.003227,0.616736,0.603459,...,265.400000,1095.320000,0.208732,0.105791,0.245094,0.154531,0.096810,0.112793,0.047421,0.000000
max,190.886307,65.156548,0.555433,2.885300,758455.187500,896604.812500,2.886312e+06,0.041835,0.998187,1.031707,...,308.050000,1276.530000,0.264843,0.218346,0.717188,0.476204,0.300217,0.320880,0.165440,1.000000

In [6]:
# info about features, their data type
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 486 entries, 0 to 485
Data columns (total 50 columns):
pop                       486 non-null float64
emp                       486 non-null float64
emp_to_pop_ratio          486 non-null float64
hc                        486 non-null float64
ccon                      486 non-null float64
cda                       486 non-null float64
cn                        486 non-null float64
ck                        486 non-null float64
ctfp                      486 non-null float64
cwtfp                     486 non-null float64
rconna                    486 non-null float64
rdana                     486 non-null float64
rnna                      486 non-null float64
rkna                      486 non-null float64
rtfpna                    486 non-null float64
rwtfpna                   486 non-null float64
labsh                     486 non-null float64
irr                       486 non-null float64
delta                     486 non-null float64
xr                        486 non-null float64
pl_con                    486 non-null float64
pl_da                     486 non-null float64
pl_gdpo                   486 non-null float64
csh_c                     486 non-null float64
csh_i                     486 non-null float64
csh_g                     486 non-null float64
csh_x                     486 non-null float64
csh_m                     486 non-null float64
csh_r                     486 non-null float64
pl_c                      486 non-null float64
pl_i                      486 non-null float64
pl_g                      486 non-null float64
pl_x                      486 non-null float64
pl_m                      486 non-null float64
pl_n                      486 non-null float64
total                     486 non-null float64
excl_energy               486 non-null float64
energy                    486 non-null float64
metals_minerals           486 non-null float64
forestry                  486 non-null float64
agriculture               486 non-null float64
fish                      486 non-null float64
total_change              486 non-null float64
excl_energy_change        486 non-null float64
energy_change             486 non-null float64
metals_minerals_change    486 non-null float64
forestry_change           486 non-null float64
agriculture_change        486 non-null float64
fish_change               486 non-null float64
growthbucket              486 non-null int64
dtypes: float64(49), int64(1)
memory usage: 189.9 KB

In [7]:
# pairplot
scatter_matrix(data[['battery_power', 'ram', 'price_range']], c=data['price_range'], figsize=(15,15))

KeyError: "None of [Index(['battery_power', 'ram', 'price_range'], dtype='object')] are in the [columns]"

In [ ]:
# correlation heatmap
plt.figure(figsize=(15,10))
sns.heatmap(data.corr(), annot=True)

In [ ]:
# boxplot grid
def build_grid(y, nrows, ncols):
    fig, axes = plt.subplots(nrows=nrows, ncols=ncols, figsize=(16, 16))
    for idx, ax in enumerate(axes.flat):
        sns.boxplot(x='price_range', y=y[idx], data=data, ax=ax)

In [ ]:
build_grid(['ram', 'battery_power', 'talk_time', 'int_memory'], 2, 2)

In [ ]:
def add_ones(X):
    ones = np.ones((X.shape[0], X.shape[1] + 1))
    ones[:, :-1] = X
    return ones

In [ ]:
X, y = data.iloc[:, :-1].values, data['price_range'].values
X = add_ones(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [ ]:
# scaling
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [ ]:
class Perceptron:
    
    def __init__(self, param_dim, num_labels):
           self.params = np.random.randn(num_labels,
                                         param_dim)
            
    def predict(self, X):
          return np.argmax(self.params.dot(X), axis=0)
        
    def load_params(self, params):
        self.params = params
        
    def train(self, X, y, num_iters=100, X_val=None, y_val=None):
        best_accuracy = 0
        if X_val is None:
            X_val = X
            y_val = y
                
        for iter_num in range(num_iters):
            for i in range(len(X)):
                prediction = self.predict(X[i])
                if prediction != y[i]:
                    self.params[prediction] -= X[i]
                    self.params[y[i]] += X[i]
                    
            val_prediction = self.predict(X_val.T)
            iter_accuracy = np.sum(val_prediction == y_val) / len(val_prediction)
            if iter_accuracy > best_accuracy:
                best_accuracy = iter_accuracy
                cached_params = np.copy(self.params)
                
        return (best_accuracy, cached_params)

In [ ]:
param_dim = X_train.shape[1]
perceptron = Perceptron(param_dim=param_dim, num_labels=4)

In [ ]:
val_accuracy, params = perceptron.train(X_train, y_train, X_val=X_test, y_val=y_test, num_iters=2000)

In [ ]:
print('Best accuracy on validation set: ', val_accuracy)

In [ ]:
perceptron.load_params(params)

In [ ]:
train_pred = perceptron.predict(X_train.T)
train_accuracy = np.sum(train_pred == y_train) / len(train_pred)

In [ ]:
print('Accuracy on training set: ', train_accuracy)